config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'  
  get '/profile' => 'pages#profile'
  get '/works' => 'pages#works'
  get '/contact' => 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark">
    <div class="container footer text-center">
        <h2 class="text-white">Contact</h2>
        <%= link_to image_tag("footer/github-icon.png", class: "rounded-circle images"), "/" %>
        <%# https://github.com/TaigaWatanabe?tab=repositories %>
        <%= link_to image_tag('footer/twitter-icon.png', class: "rounded-circle images"), "/" %>
        <%# https://twitter.com/taiga_traveler %>
        <%= link_to image_tag('footer/instagram-icon.jpeg', class: "rounded-circle images"), "/" %>
        <%# https://www.instagram.com/travel_world_2025/?hl=ja %>
        <%= link_to image_tag('footer/facebook-icon.png', class: "rounded-circle images"), "/" %>
        <%# https://www.facebook.com/profile.php?id=100028249238643 %>
        <%= mail_to 'user@example.com',image_tag('footer/mail-icon.png', class: "rounded-circle images") %>
        <%# 1208taiga@gmail.com %>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header-top">
    <div class="pos-f-t">    
        <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark font-weight-bold">
                <div class="container">
                    <h1 class="navbar-brand header-name">TW</h1>        
                <!-- right side select something -->
                    <form class="form-inline my-2 my-lg-0">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active mr-3">
                                <%= link_to root_path, class: "nav-link" do %>            
                                    <p class="select">HOME<br>ホーム</p>                            
                                <% end %>
                            </li>
                            <li class="nav-item active mr-3">
                                <%= link_to profile_path, class: "nav-link" do %>                    
                                    <p class="select">PROFILE<br>プロフィール</p>
                                <% end %>
                            </li>
                            <li class="nav-item active mr-3">
                                <%= link_to works_path, class: "nav-link" do %>                    
                                    <p class="select">WORKS<br>作品</p>
                                <% end %>
                            </li>                                            
                        </ul>
                    </form>            
                    </div>
                </div>
            </nav>
        </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
        <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        </div>
        </nav>    
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taiga's Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
    <div class="home-letter">
        <div class="container">
            <div class="home-mid text-light font-italic">
                <h1>Taiga Watanabe</h1>
                <h2>Portfolio</h2>
            </div>        
        </div>
    </div>
    <div class="bg-light">
        <div class="container text-center home-content pt-5 pb-5">          
            <a class="btn">
                <span class="btn__text"><h1>My strong points</h1></span><!-- default letter -->
                <span class="btn__text"><h2>私の強み</h2></span><!-- display letter when we hover -->
            </a>    
            <a class="btn mt-5">
                <span class="btn__text"><h3>Continuity</h3></span>
                <span class="btn__text"><h3>継続力</h3></span>
            </a>  
            <a class="btn mt-3 mb-3">
                <span class="btn__text"><h3>Ability to take action</h3></span>
                <span class="btn__text"><h3>行動力</h3></span>
            </a> 
            <a class="btn">
                <span class="btn__text"><h3>Interested in various things</h3></span>
                <span class="btn__text"><h3>様々な事に興味を持つ</h3></span>
            </a>                         
        </div>
    </div>
</div>

app/views/pages/profile.html.erb
<div class="profile bg-light">
    <div class="container font-italic">
        <div class="introduce">
            <h1>About me</h1>
            <%= image_tag 'taiga.jpg', class: "rounded-circle mt-2 mr-4 mb-5" %>
            <div class="detail">
                <h4>NAME(名前) : Watanabe Taiga (渡邊 大賀)</h4>
                <h4>FROM(出身地) : Nagoya(名古屋)</h4>
                <h4>AGE(年齢) : 23</h4>
                <h4>HOBBYS(趣味) : Squba diving(スキューバダイビング) Travel(旅行)</h4>                                
            </div>
        </div>
        <div class="skills">
            <h1>IT Skills</h1>
            <div class="row row-cols-4 ">
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/html-icon.png', class: "card-img-top" %>                    
                    <div class="card-body">
                        <h5 class="card-title">HTML5</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/css-icon.png', class: "card-img-top" %>
                    <div class="card-body">
                        <h5 class="card-title">CSS3</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/javascript-icon.png', class: "card-img-top" %>
                    <div class="card-body">
                        <h5 class="card-title">Javascript</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/ruby-icon.png', class: "card-img-top" %>
                    <div class="card-body">
                        <h5 class="card-title">Ruby</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/rails-icon.png', class: "card-img-top" %>
                    <div class="card-body">
                        <h5 class="card-title">Ruby on rails</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/github-icon2.png', class: "card-img-top" %>
                    <div class="card-body">
                        <h5 class="card-title">GitHub</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/git-icon.png', class: "card-img-top" %>                    
                    <div class="card-body">
                        <h5 class="card-title">git</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/docker-icon.png', class: "card-img-top" %>
                    <div class="card-body">
                        <h5 class="card-title">Docker</h5>
                    </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                    <%= image_tag 'IT/Mysql-icon.png', class: "card-img-top" %>
                    <div class="card-body">
                        <h5 class="card-title">MySQLWORKbench</h5>
                    </div>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>

app/views/pages/works.html.erb
<div class="works bg-light">
    <div class="container font-italic text-center">
        <h1 class="mb-5">My Works</h1>
        <div class="card-deck">
            <%# work-1 %>
            <div class="card hide">
                <%= image_tag "coffee-shop.png",class: "card-img-top" %>
                <%# <img src="images/coffee-shop.png" class="card-img-top" alt="..."> %>
                <div class="card-body">
                    <h5 class="card-title">Coffee Shop</h5>
                    <p class="card-text">This is my first website. You can make a reservation by entering name, phone-number, how many guests, date. You can use a credit card in booking time.</p>
                    <%= link_to "Go to Web site", "https://taigawatanabe.github.io/coffeebean/index.html", class: "btn btn-primary",target: :_blank%>
                </div>
                <div class="hide2">
                    <div class="hide3">HTML<br>CSS</div>
                </div>
            </div>
            <%# /work-1 %>
            <%# work-2 %>
            <div class="card hide">
                <%= image_tag "E-learning.png",class: "card-img-top" %>
                <%# <img src="images/coffee-shop.png" class="card-img-top" alt="..."> %>
                <div class="card-body">
                    <h5 class="card-title">Elearning system</h5>
                    <p class="card-text">This is my first application that can learn words. I also made signin, signout, signup functions etc.. You can try it!<br><br>Email : admin@gmail.com<br>Password : password</p>
                    <%= link_to "Go to Web site", "https://taiga-els.herokuapp.com/", class: "btn btn-primary",target: :_blank%>
                </div>
                <div class="hide2">
                    <div class="hide3">HTML,CSS,Ruby,Ruby on Rails,MySQL,Git,Github,Docker</div>
                </div>
            </div>
            <%# /work-2 %>
            <%# work-3 %>
            <div class="card hide">
                <%= image_tag "T-Airbnb.png",class: "card-img-top" %>                
                <div class="card-body">
                    <h5 class="card-title">Air-bnb clone</h5>
                    <p class="card-text">This web site kind of like airbnb. If you make your account to make and reservation rooms, you can choice room type, house type, bathroom numbers and so on. If you wanna try it you can do !<br><br>Email : whimsicaltraveler2020@gmail.com<br>Password : password</p>
                    <%= link_to "Go to Web site", "https://airbnb-taiga.herokuapp.com/", class: "btn btn-primary",target: :_blank%>
                </div>
                <div class="hide2">
                    <div class="hide3">HTML,CSS,Ruby,<br>Ruby on Rails,MySQL,Git,Github,<br>Docker,Javascript,jQuery</div>
                </div>
            </div>
            <%# /work-3 %>
        </div>
    </div>
</div>